### PR TITLE
Add updated video to website

### PR DESCRIPTION
**Pull request by egrace479**
This adds the updated Challenge introduction video (with all institutes).

### CODE REVIEW

**Comment by dboghrat** [comment]
Here is video from YouTube
<iframe width="560" height="315" src="https://www.youtube.com/embed/6NNO0SVhL2c?si=z2LaTUYd46Hlp_un" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

**Comment by katyagovorkova** [comment]
@dboghrat is it the same video that @egrace479 has pointed to? Thanks

**Comment by dboghrat** [comment]
@katyagovorkova Whatever is on there now is the old one. It should go to the YouTube link I provided. Thanks!

**Comment by egrace479** [comment]
@katyagovorkova, I also updated the "how to participate" page to add Imageomics and iHarp challenges, though you may want to make it prettier than just the list I set up. 

Additionally, I pointed the button on the main page for "Participate in the Anomaly Challenge" to link to the "How to Participate" page.

**Comment by katyagovorkova** [comment]
@egrace479 are you planning to add anything else to this MR or should I merge?

**Comment by egrace479** [comment]
@katyagovorkova, I don't intend more changes with this; please feel free to merge whenever you're ready.

**Pull request merged**
